@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "DukePasswordManager",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1034538169 { 
   	label=DukePasswordManager
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   DukePasswordManager1034538169[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DukePasswordManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_283885470 { 
   	label=user_interaction
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   UserInterface1306808093[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserInterface</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ printMessage(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ prompt(message: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

WorkflowExecutor1306808093[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)WorkflowExecutor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credentialGathering: CredentialGathering [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ executeWorkflows()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_23675889 { 
   	label=workflow
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   CreateCredentialWorkflow1032939626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CreateCredentialWorkflow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credentialGathering: CredentialGathering [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- promptAndSetPassword(credential: Credential)</TD></TR>
<TR><TD ALIGN="LEFT" >- promptAndSetUsername(credential: Credential)</TD></TR>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CredentialLoadWorkflow1032939626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CredentialLoadWorkflow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credentialGathering: CredentialGathering [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

EnterMasterPasswordWorkflow1032939626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EnterMasterPasswordWorkflow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ExitWorkflow1032939626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ExitWorkflow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credentialGathering: CredentialGathering [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SaveCredentialsWorkflow1032939626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SaveCredentialsWorkflow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credentialGathering: CredentialGathering [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowCredentialWorkflow1032939626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowCredentialWorkflow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credentialGathering: CredentialGathering [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TitleScreenWorkflow1032939626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TitleScreenWorkflow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

WorkflowSelectionWorkflow1032939626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)WorkflowSelectionWorkflow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credentialGathering: CredentialGathering [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nextWorkflow: Workflow [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- createSelectableWorkflowsMessage(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_940600548 { 
   	label=step
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   TextStep1103930615[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TextStep</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   text: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInterface: UserInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

subgraph cluster_683415465 { 
   	label=credential
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Credential763399844[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Credential</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   password: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   title: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   username: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ fieldContentIsSafe(fieldContent: String): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CredentialGathering763399844[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CredentialGathering</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credentials: List&lt;Credential&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createCredential(title: String): Credential</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
CredentialGathering763399844 -> Credential763399844[label="credentials
[0..*]"];
DukePasswordManager1034538169 -> WorkflowExecutor1306808093[label="main() -> executeWorkflows()"];
TitleScreenWorkflow1032939626 -> CreateCredentialWorkflow1032939626[arrowhead=none];
TitleScreenWorkflow1032939626 -> CredentialLoadWorkflow1032939626[arrowhead=none];
TitleScreenWorkflow1032939626 -> EnterMasterPasswordWorkflow1032939626[arrowhead=none];
TitleScreenWorkflow1032939626 -> ExitWorkflow1032939626[arrowhead=none];
TitleScreenWorkflow1032939626 -> SaveCredentialsWorkflow1032939626[arrowhead=none];
TitleScreenWorkflow1032939626 -> ShowCredentialWorkflow1032939626[arrowhead=none];
TitleScreenWorkflow1032939626 -> TextStep1103930615[label="start() -> execute()"];
TitleScreenWorkflow1032939626 -> UserInterface1306808093[label="userInterface
[0..1]"];
TitleScreenWorkflow1032939626 -> WorkflowSelectionWorkflow1032939626[arrowhead=none];
WorkflowExecutor1306808093 -> CredentialGathering763399844[label="credentialGathering
[0..1]"];
WorkflowExecutor1306808093 -> CredentialLoadWorkflow1032939626[label="executeWorkflows() -> start()"];
WorkflowExecutor1306808093 -> EnterMasterPasswordWorkflow1032939626[label="executeWorkflows() -> start()"];
WorkflowExecutor1306808093 -> TitleScreenWorkflow1032939626[label="executeWorkflows() -> start()"];
WorkflowExecutor1306808093 -> UserInterface1306808093[label="userInterface
[0..1]"];
WorkflowExecutor1306808093 -> WorkflowSelectionWorkflow1032939626[label="executeWorkflows() -> start()"];
    
}
@enduml